# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25278fa3d47e3befef6d4802d7239d3d7e43cfbcb8d7dee2bf61e308c9fa6740fc48faea72e2f86073d9b03638e56f842e7405e263895d220878e33606122b38

test:
  secret_key_base: f73b19d1e10a7e919d70aa05b8af85046e29cfdd1d9ad35d4bb6c1df10baf743d35bfbf5f9c0709c369e151ac5cb2b013743fad29bd83e7dcede4670347cd62d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 66364cc66f069c997bef8face39f48b6ed834ac6296654c488e29aa5560c402aafbb9ead454233850061c88b519b3efacf11e71d50dcabcae25bef8f560c4c4b
